obj-m := hello.o

all:
	make -C /home/lwl/LWL/MyCourses/VirtualBoard/virtualboard/kernel/linux-6.6.11 M=${PWD} modules
clean:
	make -C /home/lwl/LWL/MyCourses/VirtualBoard/virtualboard/kernel/linux-6.6.11 M=${PWD} clean
